version: '3.8'

services:
  ef-migrations:
    image: ef-migrations
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__ProductsDbContext: "Server=db; Database=ProductsDb; User=sa; Password=MyStrong@Passw0rd; Integrated Security=False"
    depends_on:
      - db

  db:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyStrong@Passw0rd"
      ACCEPT_EULA: "Y"

# docker-compose build
# docker-compose up -d
# docker-compose ps
# docker-compose logs ef-migrations
# docker-compose down
